name: erp_mobile_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_riverpod: ^2.5.1
  go_router: ^13.0.0
  dio: ^5.4.0
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.0.0
  cupertino_icons: ^1.0.8
  fl_chart: ^0.63.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/image.png


